package UI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author jhony
 */
import irrgarten.Directions;

public class Cursors extends javax.swing.JDialog {
private Directions direction;
    /**
     * Creates new form Cursors
     */
    public Cursors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IZQUIERDA = new javax.swing.JButton();
        DERECHA = new javax.swing.JButton();
        ARRIBA = new javax.swing.JButton();
        ABAJO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        IZQUIERDA.setText("IZQUIERDA");
        IZQUIERDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IZQUIERDAActionPerformed(evt);
            }
        });

        DERECHA.setText("DERECHA");
        DERECHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DERECHAActionPerformed(evt);
            }
        });

        ARRIBA.setText("ARRIBA");
        ARRIBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARRIBAActionPerformed(evt);
            }
        });

        ABAJO.setText("ABAJO");
        ABAJO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABAJOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IZQUIERDA)
                .addGap(158, 158, 158)
                .addComponent(DERECHA))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ABAJO)
                    .addComponent(ARRIBA)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ARRIBA)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IZQUIERDA)
                    .addComponent(DERECHA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ABAJO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IZQUIERDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IZQUIERDAActionPerformed
        // TODO add your handling code here:
        direction=Directions.LEFT;
        dispose();
    }//GEN-LAST:event_IZQUIERDAActionPerformed

    private void DERECHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DERECHAActionPerformed
        // TODO add your handling code here:
        direction=Directions.RIGHT;
        dispose();
    }//GEN-LAST:event_DERECHAActionPerformed

    private void ARRIBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARRIBAActionPerformed
        // TODO add your handling code here:
        direction=Directions.UP;
        dispose();
    }//GEN-LAST:event_ARRIBAActionPerformed

    private void ABAJOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABAJOActionPerformed
        // TODO add your handling code here:
        direction=Directions.DOWN;
        dispose();
    }//GEN-LAST:event_ABAJOActionPerformed

    /**
     * @param args the command line arguments
     */
   public Directions getDirection(){
       setVisible(true);
       return direction;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABAJO;
    private javax.swing.JButton ARRIBA;
    private javax.swing.JButton DERECHA;
    private javax.swing.JButton IZQUIERDA;
    // End of variables declaration//GEN-END:variables
}
